config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/users/auth/sign_up' => 'omniauth_callbacks#sign_up'
  end

  root 'questions#index'

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :vote_reset
    end
  end

  concern :commentable do
    member do
      post :comment
    end
  end

  resources :questions, shallow: true do
    concerns :votable
    concerns :commentable
    resources :answers, only: [:create, :update, :destroy] do
      concerns :votable
      concerns :commentable
      patch :set_best, on: :member
    end
    put :vote_up, on: :member
  end

  resources :attachments, only: [:destroy]
  resources :subscriptions, only: [:create, :destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  get '/search' => 'search#search'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  validates :title, :body, presence: true

  default_scope { order(:id) }

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  accepts_nested_attributes_for :attachments,
                                reject_if: :all_blank,
                                allow_destroy: true

  after_create :subscribe_author

  def subscribed?(user)
    self.subscriptions.where(user: user).exists?
  end

  private

  def find_subscription(user)
    subscriptions.where(user: user).first
  end

  def subscribe_author
    Subscription.create!(user: user, question: self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question
  end

  def create
    respond_with(@question = current_resource_owner.questions.create(question_params))
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Votabled
  include Commentabled

  before_action :authenticate_user!, except: [:index, :show]
  before_action :get_question, only: [:show, :edit, :update, :destroy]
  before_action :build_answer, only: [:show]
  after_action :publish_question, only: [:create]

  authorize_resource

  respond_to :js, only: [:show, :update]

  def index
    respond_with(@questions = Question.all)
  end

  def show
    gon.question_id = @question.id
    gon.question_user_id = @question.user_id
    @subscription = @question.subscriptions.find_by(user_id: current_user.id) if current_user
    respond_with(@question)
  end

  def new
    respond_with(@question = Question.new)
  end

  def edit
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    respond_with(@question.destroy!)
  end

  private

  def get_question
    @question = Question.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def question_params
    params.require(:question).permit(:title,
                                     :body,
                                     attachments_attributes: [:id,
                                                              :file,
                                                              :_destroy])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question',
        locals: { question: @question }
      )
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.slim
- @question.answers.each do |answer|
  = render 'answers/answer', answer: answer

app/views/questions/_attachment_fields.html.slim
.nested-fields
  =f.label :file
  =f.file_field :file

app/views/questions/_comment.html.slim
- if item.comments.any?
  .panel-heading
    h3 = 'All comments:'
.comments-list.panel-body
  - item.comments.each do |comment|
    p id = "comment_#{comment.id}"
      - cache comment do
        = comment.body

- if can?(:create, Comment)
  p = link_to 'Leave a comment', '', class: 'btn btn-primary add-comment'

p.comment_errors.bg-danger
- cache ['comment_form', item]
  = simple_form_for([item, item.comments.build], url: url, remote: true) do |f|
    .form-group.col-md-12
      = f.input :body, label: 'Your comment'
    = f.submit 'Add comment', class: 'btn btn-success'

app/views/questions/_form_question.html.slim
- if can?(:update, @question)
  = link_to 'Delete', @question,
                      data: { method: :delete, confirm: t('you_sure') },
                      remote: true

  = link_to 'Edit', '', class: 'edit-question-link',
                        data: { question_id: @question.id }

  = simple_form_for [@question], remote: true, html: { id: "edit-question-#{@question.id}"} do |f|
    = f.input :title, label: 'Question title'
    = f.input :body, label: 'Question body'
    p.question-errors.bg-danger
    = f.submit 'Save'

app/views/questions/_question.html.slim
.question-item id = "question-#{question.id}"
  - if question.persisted?
    p.list-group-item
      = link_to question.title, question_path(question.id),
      class: 'question-title-link'
    p = question.body

app/views/questions/_question_show.html.slim
- cache @question do
  .panel-heading
    h1 = @question.title

  .panel-body
    p = link_to 'Back to questions', questions_path
    = render 'form_question'
    p = render 'vote', item: @question

    hr

    h2 = 'Question body'
    p = @question.body

    hr

    - if @question.attachments.any?
      b Attachments:
      ul.question-files
        - @question.attachments.each do |a|
          li id="attachment-#{a.id}"
            = link_to a.file.identifier, a.file.url
            - if can?(:destroy, @question)
              = link_to 'remove attachment', attachment_path(a),
                                             method: :delete,
                                             remote: true

  .question-comments.panel.panel-default
    = render 'questions/comment', item: @question, url: comment_question_path(@question)

app/views/questions/_subscription.html.slim
.subscription
  - if @question.subscribed?(current_user)
    = link_to 'Unsubscribe', subscription_path(@subscription), method: :delete, remote: true
  - else
    = link_to 'Subscribe', subscriptions_path(subscription: { question_id: @question.id }), method: :post, remote: true

app/views/questions/_vote.html.slim
.votes id = "#{item.id}"
  .btn-group
    - if can?(:votes, item)
      - unless current_user&.author_of?(item)
        = link_to '+', polymorphic_path(item, action: :vote_up),
          remote: true,
          data: { type: :json },
          method: :post,
          class: 'btn btn-success'

        = link_to 'vote reset', polymorphic_path(item, action: :vote_reset),
          remote: true,
          data: { type: :json },
          method: :delete,
          class: 'btn btn-default'

        = link_to '-', polymorphic_path(item, action: :vote_down),
          remote: true,
          data: { type: :json },
          method: :post,
          class: 'btn btn-danger'

  p.vote-count = item.rating

app/views/questions/comment.js.erb
<% if @comment.errors.present? %>
  <% @comment.errors.full_messages.each do |message| %>
    $('.question .comment_errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('textarea#comment_body').val('');
  $('.question .add-comment').show();
  $('.question .new_comment').hide();
<% end %>

app/views/questions/index.html.slim
h1 = 'All questions'

- if can?(:create, Question)
  p
    = link_to 'Ask question', new_question_path, class: 'btn btn-primary'

- cache collection_cache_key_for :question do
  .list-group.questions-list
    - @questions.each do |question|
      = render question

app/views/questions/new.html.slim
h1 = 'Создать вопрос'

= simple_form_for @question do |f|
  = f.input :title
  = f.input :body

  b Attachments:
  #attachments
    = f.simple_fields_for :attachments, @question.attachments.build do |attachment|
      = render 'attachment_fields', f: attachment
    .links
      = link_to_add_association 'add attachment', f, :attachments
  =f.submit 'Create'

app/views/questions/show.html.slim
div id = "question-#{@question.id}"
  .panel.panel-default.question
    = render 'question_show'
  - if can?(:create, Subscription) || can?(:destory, Subscription)
    p = render 'subscription'

  .answers
    h2 = 'Все ответы на вопрос:'
    = render 'answers/answers'

  - if user_signed_in?
    p.answer-errors.bg-danger
    = render 'answers/form_answer'

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question-errors').html('<%= j message %>')
<% end %>
<% else %>
  $('div.question').html('<%= j render "question_show" %>');
<% end %>