config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/users/auth/sign_up' => 'omniauth_callbacks#sign_up'
  end

  root 'questions#index'

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :vote_reset
    end
  end

  concern :commentable do
    member do
      post :comment
    end
  end

  resources :questions, shallow: true do
    concerns :votable
    concerns :commentable
    resources :answers, only: [:create, :update, :destroy] do
      concerns :votable
      concerns :commentable
      patch :set_best, on: :member
    end
    put :vote_up, on: :member
  end

  resources :attachments, only: [:destroy]
  resources :subscriptions, only: [:create, :destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  get '/search' => 'search#search'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  after_create :notify_subscribers

  validates :body, presence: true

  belongs_to :user
  belongs_to :question, touch: true

  has_many :attachments, as: :attachable, dependent: :destroy

  accepts_nested_attributes_for :attachments,
                                reject_if: :all_blank,
                                allow_destroy: true

  default_scope { order(best: :desc, created_at: :asc) }

  def set_best
    Answer.transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end

  private

  def notify_subscribers
    NotifySubscribersJob.perform_later(self.question)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Votabled
  include Commentabled

  before_action :authenticate_user!
  before_action :get_question, only: [:create]
  before_action :get_answer, only: [:update, :destroy, :set_best]
  after_action :publish_answer, only: [:create]

  authorize_resource

  respond_to :js
  respond_to :json, only: :create

  def create
    @answer = @question.answers.create(answer_params.merge(user_id: current_user.id))
  end

  def update
    respond_with(@answer.update(answer_params))
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def set_best
    respond_with(@answer.set_best)
  end

  private

  def get_question
    @question = Question.find(params[:question_id])
  end

  def get_answer
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def answer_params
    params.require(:answer).permit(:body,
                                   attachments_attributes: [:file,
                                                            :id,
                                                            :_destroy])
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
        "questions/#{@question.id}/answers",
        ApplicationController.render(
            partial: "answers/answer",
            formats: :json,
            locals: { answer: @answer }
        )
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource
  before_action :load_question, except: :show

  def index
    @answers= @question.answers
    respond_with @answers
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer
  end

  def create
    @answer = Answer.create(answer_params.merge(question: @question,
                                                user: current_resource_owner))
    respond_with @answer
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def load_question
    @question = Question.find(params[:question_id])
  end
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  .panel.panel-default.answer id = "answer-#{answer.id}"
    - if answer.best?
      span.glyphicon.glyphicon-star.answer-best
    .panel-body
      = answer.body
      = render 'questions/vote', item: answer

    - if answer.attachments.any?
      ul.answer-files
        - answer.attachments.each do |a|
          li id="attachment-#{a.id}"
            = link_to a.file.identifier, a.file.url
            - if can?(:destroy, answer)
              = link_to 'Remove attachment', attachment_path(a),
                method: :delete,
                remote: true,
                class: 'delete-attachment-link'
    .answer-comments
      = render 'questions/comment', item: answer, url: comment_answer_path(answer)

    - if can?(:set_best, answer) && !answer.best
      = link_to 'Set best', set_best_answer_path(answer),
        remote: true,
        method: :patch,
        class: 'set-best-answer-link'

    - if can?(:update, answer) && can?(:destroy, answer)
      hr

      = link_to 'Delete', answer,
        data: { method: :delete, confirm: t('you_sure') },
        remote: true,
        class: 'delete-answer-link'

      = link_to 'Edit', '',
        data: { answer_id: answer.id },
        remote: true,
        class: 'edit-answer-link'

    = simple_form_for [answer], remote: true, html: { id: "edit-answer-#{answer.id}"} do |f|
      = f.input :body, label: 'Answer'
      = f.submit 'Save'

app/views/answers/_answers.html.slim
= render @question.answers

app/views/answers/_form_answer.html.slim
= simple_form_for [@question, @answer], remote: true do |f|
  = f.input :body, label: 'Your answer'

  #attachments
    = f.simple_fields_for :attachments, @answer.attachments.build do |attachment|
      = render 'attachment_fields', f: attachment
    .links
      = link_to_add_association 'add attachment', f, :attachments

  = f.submit 'Create'

app/views/answers/comment.js.erb
<% if @comment.errors.present? %>
  <% @comment.errors.full_messages.each do |message| %>
    $('.answer .comment_errors').html('<%= j message %>');
  <% end %>
  <% else %>
    $('.answer textarea#comment_body').val('');
    $('.answer .add-comment').show();
    $('.answer .new_comment').hide();
<% end %>

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').append('<%= j render @answer %>');
  $('.answer_body #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.delete-answer-link').bind('ajax:success', function() {
  $(this).closest('.answer').fadeOut();
});

app/views/answers/set_best.js.erb
$('.answers').html('<%= j render 'questions/answers' %>');

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>')
  <% end %>
<% else %>
  $('#answer-' + <%= @answer.id %> ).replaceWith('<%= j render @answer %>');
<% end %>